
apiVersion: v1

kind: Secret

metadata:

  name: odoo-secret

  namespace: odoo-test

type: Opaque

stringData:

  AWS_HOST: "http://192.168.2.171:4566"
  AWS_S3_ENDPOINT: "http://192.168.2.171:4566"
  AWS_ENDPOINT_URL: "http://192.168.2.171:4566"
  AWS_REGION: "us-east-1"
  AWS_S3_REGION_NAME: "us-east-1"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
  AWS_BUCKETNAME: "odoo-test-filestore"
  AWS_S3_BUCKET_NAME: "odoo-test-filestore"
  AWS_S3_USE_SSL: "false"
  AWS_S3_SECURE: "false"
  ODOO_CLOUD_PLATFORM_UNSAFE: "1"
